import { gql } from '@apollo/client';

export const QUERY_ME = gql`
  query Me {
    me {
      _id
      username
    }
  }
`;

export const QUERY_ASSESSMENT = gql`
  query assessment($hullNumber: String) {
    assessment(hullNumber: $hullNumber) {
      hullNumber
      hull {
        fiberglass
        gelCoat
        paint
        preservation
      }
      sponson {
        tube
        mbcs
        retainers
        transomStraps
        sponsonGasket
      }
      propulsion {
        outdrive 
        outdrivePaint 
        propeller 
        tillerBracket 
        trimHoses 
        trimCylinders 
        outdriveZincs
        outdriveGrounding
        bellows
        outdriveReservoir
        interiorTrimHose
        trimPump
        trimSolenoids
        trimBracket
        driveshaft
        aftHoop
        aftBearing
        forwardHoop
        forwardBearing
        shiftCables
        throttleCable
        cableBracket
        controlHead
        throttlePlacard
      }
      piping {
        seacock 
        seacockHose
        strainer 
        strainerHose
        fuelHoses 
        fuelStripping 
        flocs 
        racorHousing
        racorFilter
        fuelTank
        exhaustHose
      }
      engine {
        enginePaint
        engineOil
        oilFilter
        oilHoses
        fuelFilter
        fuelHoses
        coolant
        coolantCap
        waterPump
        afterCooler
        heatExchanger
        waterHoses
        zincs
        starter
        alternator
        ecm
        motorMounts
        mountingBrackets
        turbo
        turboOilLine
        turboCoolantLine
        waterBelt
        driveBelt
        beltGuard
      }
      electrical {
        navLights
        anchorLight
        horn
        bilgePump
        pumpLed
        floatSwitch
        controlSwitches
        trimSwitches
        trimGauge
        trimLed
        trimPump
        chargingBreaker
        preHeaterBreaker
        polarityLed
        vhfRadio
        vhfAntenna
        gps
        smartcraft
        whelenControl
        whelenMic
        whelenSpeaker
        strobe
        spotlight
        receptacles
        mobiDisplay
        mobiPower
        mobiData
        mobiAntenna
        barrelSwitch
        batteries
        batteryCables
        batteryCharger
        interiorBreakers
      }
      deck {
        nonskid
        fwdHatchGasket
        fwdHatchHinge
        fwdHatchLatch
        fwdHatchStopper
        archStowage
        archFrame
        centerLifeline
        fwdSeatCushion
        fwdSeatGasket
        fwdSeatHinges
        fwdSeatLatches
        consoleSupportPost
        consoleDeckGasket
        consoleDeckLatches
        consoleDeckHinges
        stbdAccessGasket
        stbdAccessHinges
        stbdAccessBolts
        aftAccessGasket
        aftAccessHinges
        aftAccessBolts
        vhfCover
        gpsCover
        smartcraftCover
        mobiCover
        vhfMicClip
        whelenMicClip
        handrails
        handrailPushpins
        consolePreservation
        coxianCaulk
        aftStowageCushion
        aftStowageGasket
        aftStowageHinges
        aftStowageLatches
        aftBilgeGasket
        aftBilgeHinges
        aftBilgeLatches
        ringBracket
        manualPump
        manualPumpHandle
        mobiPost
        mobiPostPin
        sternPost
        sternPin
        transomCap
        transomCaulk
        scuppers
      }
    }
  }
`;